type Todo {
  id: ID!
  content: String!
  status: Boolean!
}

type MutationCompletedReturnType {
  mutationType: String!
  username: String!
  todo: Todo!
}

input TodoInput {
  id: ID!
  content: String!
  status: Boolean!
}

type Query {
  todos: [Todo!]!
}

type Mutation {
  createTodo(content: String!): String!
  editTodoContent(id: ID!, newContent: String!): String!
  toggleTodoStatus(id: ID!, newStatus: Boolean!): String!
  deleteTodo(id: ID!): String!
  mutationCompleted(
    mutationType: String!
    username: String!
    todo: TodoInput!
  ): MutationCompletedReturnType!
}

type Subscription {
  onMutationCompleted(username: String): MutationCompletedReturnType
    @aws_subscribe(mutations: ["mutationCompleted"])
}
